language: ruby
rvm: 2.2
cache:
  directories:
  - vendor/bundle
bundler_args: --deployment
install: script/install --deploy
script: script/build
branches:
  only:
    - site
env:
  global:
  - secure: rVEyX2g5nJg4yjZIGylOxPRtg3VWRZcmdVgwtbhqDCR9pNPpy3P2IfPKYGoToupSjwbvcgHSzKDW+BRPdOgXwNOW85H/aU80kqZcMQ+PuAaYdbExfGluuPjwPHm0ivyL+fAGZLoCaHpH2olss/hR3XGJdKNsB8yXXAZE5LbI2bCrGGpEvCf3ZAylhq2+2jpNuSvrtyJPn5pvn9exVFpD1eiG4Z+mFejBIM2+8lIilmeDMTHpwQPDt5A/enhUr3i178S6jnhN7r+4oNkFkUag7Hw3RgZW4m76aiQaW/RCmw5Yc4FoMD9RQ16SGrGFa82RyczKraFI8jNCacZnHjXBVw1m3od2PW0CjZnIf3uUga7OZ0a2/NfI6lfpLm+UyZHWytJ8rslbDLSym74jVV1Ba2r/9nHRSwbQHaGNjiu+YYy2c2SJ8dgOr3QZHEKv5Lub/fHxbV7SnF8ywuYVo6+ekJ3T+znC6fjNTvfdoZRl0NpX3RC7bbQQ5bv+oJL4Q8pYEsAmd8bMIyqWeo+6QgLFl3dvRB1nJoSZptPlyYHgWyNJd6rVd+c6b7hvT6dAf3/06AuVUD2NMgCdoUo2y6vkXSLmBI2tl0KsXBmfzDRWThlargzNZoQSt6dY9Hk7jO81Cb/Ii36G8o6Aki4qPCfdEvKeZzGrSLD1lKaF/93WQnc=
  - PAGES_REPO_NWO=$TRAVIS_REPO_SLUG JEKYLL_GITHUB_TOKEN=$GH_TOKEN
