title: Charcoal
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - '*.sh'
  - script/*
  - '*.rb'
  - Gemfile*
  - vendor/bundle
  - .asset-cache
kramdown:
  parse_block_html: true
assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "> 1%"
  assets:
    - branding.css
gems:
  - jekyll-redirect-from
  - jekyll-avatar
url: https://charcoal-se.org
baseurl: https://charcoal-se.org
permalink: none
